# Generated by Django 5.0.14 on 2026-06-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('lista', 'Lista desplegable'), ('email', 'Correo electrónico'), ('url', 'URL'), ('telefono', 'Teléfono'), ('textarea', 'Texto largo'), ('imagen', 'Imagen'), ('archivo', 'Archivo')], max_length=20),
        ),
    ]
