# Generated by Django 5.0.14 on 2026-06-24 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0002_campo_activo_registro_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='formula',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='formulario_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campos_origen', to='dynamic_forms.formulario'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('lista', 'Lista desplegable'), ('email', 'Correo electrónico'), ('url', 'URL'), ('telefono', 'Teléfono'), ('textarea', 'Texto largo'), ('imagen', 'Imagen'), ('archivo', 'Archivo'), ('relacion', 'Relación'), ('calculado', 'Calculado')], max_length=20),
        ),
    ]
