# Generated by Django 5.0.14 on 2026-06-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0003_campo_formula_campo_formulario_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='unico',
            field=models.BooleanField(default=False, help_text='Si se activa, no pueden existir dos registros con el mismo valor en este campo.'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='hook_post_actualizar',
            field=models.TextField(blank=True, help_text='Path Python a la función post-actualización. Ej: apps.misw.hooks.post_actualizar', null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='hook_post_crear',
            field=models.TextField(blank=True, help_text='Path Python a la función post-creación. Ej: apps.misw.hooks.post_crear', null=True),
        ),
        migrations.AddField(
            model_name='formulario',
            name='validacion_personalizada',
            field=models.TextField(blank=True, help_text='Path Python a la función de validación personalizada. Recibe (formulario, valores_dict) y retorna lista de errores.', null=True),
        ),
    ]
