# Generated by Django 5.0.14 on 2026-06-26 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0004_campo_unico_formulario_hook_post_actualizar_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                # Fix 1: Formulario.creado_por_id debe ser nullable
                # (modelo dice null=True, pero BD tenía NOT NULL por estado anterior)
                'ALTER TABLE dynamic_forms_formulario '
                'ALTER COLUMN creado_por_id DROP NOT NULL;',
            ],
            reverse_sql=[
                'ALTER TABLE dynamic_forms_formulario '
                'ALTER COLUMN creado_por_id SET NOT NULL;',
            ],
            state_operations=[
                # No state operations needed — modelo ya dice null=True
            ],
        ),
        migrations.RunSQL(
            sql=[
                # Fix 2: ValorCampo.valor debe ser NOT NULL
                # (modelo dice TextField() sin null, pero BD tenía nullable)
                'ALTER TABLE dynamic_forms_valorcampo '
                'ALTER COLUMN valor SET NOT NULL;',
            ],
            reverse_sql=[
                'ALTER TABLE dynamic_forms_valorcampo '
                'ALTER COLUMN valor DROP NOT NULL;',
            ],
            state_operations=[
                # No state operations needed — modelo ya NO permite null
            ],
        ),
        migrations.RunSQL(
            sql=[
                # Fix 3: Campo.nombre debe tener max_length=100
                # (modelo dice max_length=100, pero BD tenía varchar(200))
                'ALTER TABLE dynamic_forms_campo '
                'ALTER COLUMN nombre TYPE varchar(100);',
            ],
            reverse_sql=[
                'ALTER TABLE dynamic_forms_campo '
                'ALTER COLUMN nombre TYPE varchar(200);',
            ],
            state_operations=[
                # No state operations needed — modelo ya tiene max_length=100
            ],
        ),
    ]
