# Generated by Django 5.0.14 on 2026-06-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0005_fix_schema_discrepancies'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='valorcampo',
            index=models.Index(fields=['campo', 'valor'], name='idx_valorcampo_campo_valor'),
        ),
    ]
