# Generated by Django 5.0.14 on 2026-06-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_add_valorcampo_campo_valor_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='identificador_principal',
            field=models.BooleanField(default=False, help_text='Marca este campo como el identificador principal del formulario. Solo un campo por formulario puede tener esta marca.'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('moneda', 'Moneda'), ('fecha', 'Fecha'), ('booleano', 'Booleano'), ('lista', 'Lista desplegable'), ('email', 'Correo electrónico'), ('url', 'URL'), ('telefono', 'Teléfono'), ('textarea', 'Texto largo'), ('imagen', 'Imagen'), ('archivo', 'Archivo'), ('relacion', 'Relación'), ('calculado', 'Calculado')], max_length=20),
        ),
    ]
