# Generated by Django 5.0.14 on 2026-06-27 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0007_campo_identificador_principal_alter_campo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archivo_nombre', models.CharField(max_length=500)),
                ('archivo_tamano', models.IntegerField(default=0)),
                ('archivo_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('modo', models.CharField(choices=[('crear', 'Solo crear'), ('actualizar', 'Solo actualizar'), ('upsert', 'UPSERT'), ('validar', 'Solo validar')], max_length=20)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('revertido', 'Revertido'), ('parcial', 'Parcial')], default='completado', max_length=20)),
                ('total_filas', models.IntegerField(default=0)),
                ('creados', models.IntegerField(default=0)),
                ('actualizados', models.IntegerField(default=0)),
                ('ignorados', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('tiempo_seg', models.FloatField(default=0.0)),
                ('resumen', models.TextField(blank=True)),
                ('hoja_detectada', models.CharField(blank=True, max_length=200)),
                ('confianza_global', models.FloatField(default=0.0)),
                ('calidad_estrellas', models.IntegerField(default=0)),
                ('resultado_json', models.TextField(blank=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='dynamic_forms.formulario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Importación',
                'verbose_name_plural': 'Importaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ImportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación'), ('actualizacion', 'Actualización'), ('error', 'Error'), ('advertencia', 'Advertencia'), ('decision', 'Decisión automática'), ('ignorado', 'Ignorado'), ('rollback', 'Rollback')], db_index=True, max_length=20)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('campo_nombre', models.CharField(blank=True, max_length=200)),
                ('valor_anterior', models.TextField(blank=True)),
                ('valor_nuevo', models.TextField(blank=True)),
                ('mensaje', models.TextField()),
                ('metadata_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='dynamic_forms.importlog')),
            ],
            options={
                'verbose_name': 'Auditoría de importación',
                'verbose_name_plural': 'Auditorías de importación',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valores_anteriores', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dynamic_forms.importlog')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.registro')),
            ],
            options={
                'verbose_name': 'Snapshot de importación',
                'verbose_name_plural': 'Snapshots de importación',
                'unique_together': {('import_log', 'registro')},
            },
        ),
    ]
