# Generated by Django 5.0.14 on 2026-06-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0008_importlog_importaudit_importsnapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campo',
            options={'ordering': ['orden'], 'verbose_name': 'Campo', 'verbose_name_plural': 'Campos'},
        ),
        migrations.AddField(
            model_name='campo',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción del campo para orientar al usuario.', null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='metadata_json',
            field=models.JSONField(blank=True, help_text='Configuración extendida: regex, min/max, decimales, default, placeholder, ayuda, etc.', null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='visible',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el campo no se muestra en formularios ni tablas.'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('moneda', 'Moneda'), ('porcentaje', 'Porcentaje'), ('fecha', 'Fecha'), ('hora', 'Hora'), ('fecha_hora', 'Fecha y hora'), ('booleano', 'Booleano'), ('lista', 'Lista desplegable'), ('email', 'Correo electrónico'), ('url', 'URL'), ('telefono', 'Teléfono'), ('documento', 'Documento de identidad'), ('codigo', 'Código'), ('codigo_barras', 'Código de barras'), ('qr', 'Código QR'), ('textarea', 'Texto largo'), ('imagen', 'Imagen'), ('archivo', 'Archivo'), ('relacion', 'Relación'), ('calculado', 'Calculado'), ('color', 'Color'), ('ip', 'Dirección IP'), ('uuid', 'UUID'), ('geolocalizacion', 'Geolocalización'), ('duracion', 'Duración'), ('estado', 'Estado'), ('categoria', 'Categoría'), ('tags', 'Etiquetas')], max_length=20),
        ),
        migrations.CreateModel(
            name='MappingMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers_hash', models.CharField(db_index=True, help_text='SHA256 de los nombres de columna normalizados.', max_length=64)),
                ('headers_text', models.TextField(blank=True, help_text='JSON con la lista original de encabezados.')),
                ('mapping_json', models.TextField(help_text='JSON con el mapeo {col_idx: campo_nombre}.')),
                ('confidence_avg', models.FloatField(default=0.95, help_text='Confianza promedio del mapeo almacenado.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_used', models.IntegerField(default=1, help_text='Número de veces que este mapeo ha sido reutilizado.')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_memories', to='dynamic_forms.formulario')),
            ],
            options={
                'verbose_name': 'Memoria de mapeo',
                'verbose_name_plural': 'Memorias de mapeo',
                'ordering': ['-times_used', '-updated_at'],
                'unique_together': {('formulario', 'headers_hash')},
            },
        ),
    ]
