# Generated by Django 5.0.14 on 2026-06-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='Provider slug (gemini, openrouter, deepseek, qwen)', max_length=50)),
                ('model', models.CharField(blank=True, default='', help_text='Model name used', max_length=100)),
                ('service', models.CharField(blank=True, default='', help_text='Service that triggered the analysis (e.g., field_detector)', max_length=100)),
                ('document_type', models.CharField(blank=True, default='', help_text='Type of document analyzed (excel, pdf, image, text, invoice)', max_length=50)),
                ('document_name', models.CharField(blank=True, default='', help_text='Original file name or identifier', max_length=255)),
                ('processing_time_ms', models.FloatField(default=0.0, help_text='Processing time in milliseconds')),
                ('prompt_tokens', models.IntegerField(default=0, help_text='Input tokens')),
                ('completion_tokens', models.IntegerField(default=0, help_text='Output tokens')),
                ('total_tokens', models.IntegerField(default=0, help_text='Total tokens consumed')),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0.0, help_text='Estimated cost in USD', max_digits=10)),
                ('success', models.BooleanField(default=True, help_text='Whether the analysis succeeded')),
                ('cached', models.BooleanField(default=False, help_text='Whether the result was served from cache')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if analysis failed')),
                ('confidence', models.FloatField(default=0.0, help_text='Overall confidence score (0.0 to 1.0)')),
                ('result_summary', models.TextField(blank=True, default='', help_text='Truncated summary of the analysis result (first 2000 chars)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis was performed')),
            ],
            options={
                'verbose_name': 'Registro de análisis AI',
                'verbose_name_plural': 'Registros de análisis AI',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'created_at'], name='ai_aianalys_provide_243de6_idx'), models.Index(fields=['document_type'], name='ai_aianalys_documen_7239b7_idx'), models.Index(fields=['success'], name='ai_aianalys_success_e114ea_idx')],
            },
        ),
    ]
