# Generated by Django 5.0.14 on 2026-06-29 18:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', help_text='Auto-generated or user-provided conversation title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the last message')),
                ('archived', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, default='', help_text='Latest auto-generated summary of the conversation')),
                ('metadata_json', models.TextField(blank=True, default='{}', help_text='JSON metadata for extensibility')),
                ('message_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversacion',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-last_message_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema'), ('tool', 'Herramienta')], help_text='Quien envio el mensaje', max_length=20)),
                ('content', models.TextField(blank=True, default='', help_text='Contenido del mensaje')),
                ('intent', models.CharField(blank=True, default='', help_text='Tipo de intent detectado', max_length=100)),
                ('provider', models.CharField(blank=True, default='', help_text='Provider slug (gemini, deepseek, tool, data_agent)', max_length=50)),
                ('source', models.CharField(blank=True, default='', help_text='Source: ai, tool, data_agent, heuristic', max_length=30)),
                ('confidence', models.FloatField(default=0.0)),
                ('execution_time', models.FloatField(default=0.0, help_text='Execution time in milliseconds')),
                ('token_count', models.IntegerField(default=0)),
                ('tool_name', models.CharField(blank=True, default='', help_text='Nombre de la herramienta (solo role=tool)', max_length=100)),
                ('tool_success', models.BooleanField(default=True)),
                ('tool_dry_run', models.BooleanField(default=False)),
                ('tool_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Cuando se envio el mensaje')),
                ('metadata_json', models.TextField(blank=True, default='{}', help_text='JSON metadata adicional')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
            ],
            options={
                'verbose_name': 'Mensaje de conversacion',
                'verbose_name_plural': 'Mensajes de conversacion',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='Resumen generado automaticamente')),
                ('message_count', models.IntegerField(default=0, help_text='Numero de mensajes al generar el resumen')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Cuando se genero el resumen')),
                ('metadata_json', models.TextField(blank=True, default='{}')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='ai.conversation')),
            ],
            options={
                'verbose_name': 'Resumen de conversacion',
                'verbose_name_plural': 'Resumenes de conversacion',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-last_message_at'], name='ai_conversa_user_id_ae7528_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'archived'], name='ai_conversa_user_id_224e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'pinned'], name='ai_conversa_user_id_7bf9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_conversa_convers_0e7ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationmessage',
            index=models.Index(fields=['role'], name='ai_conversa_role_f92f60_idx'),
        ),
    ]
