# Generated by Django 5.0.14 on 2026-06-29 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_conversation_conversationmessage_conversationsummary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, '👍 Util'), (-1, '👎 No util')], help_text='+1 for thumbs up, -1 for thumbs down')),
                ('reason', models.CharField(blank=True, choices=[('', 'Sin motivo'), ('incorrect', 'Informacion incorrecta'), ('incomplete', 'Respuesta incompleta'), ('slow', 'Demasiado lento'), ('hallucination', 'Alucinacion'), ('bad_format', 'Formato incorrecto'), ('unhelpful', 'No fue util'), ('other', 'Otro')], default='', help_text='Reason for negative feedback', max_length=50)),
                ('comment', models.TextField(blank=True, default='', help_text='Optional free-text comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When feedback was submitted')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification time')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai.conversation')),
                ('message', models.ForeignKey(help_text='The assistant message being rated', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ai.conversationmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retroalimentacion',
                'verbose_name_plural': 'Retroalimentaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='ai_conversa_convers_cf71ec_idx'), models.Index(fields=['message', 'user'], name='ai_conversa_message_541615_idx'), models.Index(fields=['user', 'created_at'], name='ai_conversa_user_id_e1fb83_idx'), models.Index(fields=['rating'], name='ai_conversa_rating_8a99f7_idx')],
            },
        ),
    ]
