# Generated by Django 5.0.14 on 2026-06-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_cliente_apellido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido']},
        ),
    ]
