# Generated by Django 5.0.14 on 2026-06-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_cliente_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
