"""
types.py — Core type definitions for the AI module.

All data structures used across providers, services, and schemas.
Independent of any specific provider or framework.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional


# ======================================================================
# Provider identifiers
# ======================================================================

class ProviderType(str, Enum):
    GEMINI = "gemini"
    OPENROUTER = "openrouter"
    DEEPSEEK = "deepseek"
    QWEN = "qwen"

    @classmethod
    def from_string(cls, value: str) -> ProviderType:
        for member in cls:
            if member.value == value.lower():
                return member
        return cls.GEMINI  # fallback


# ======================================================================
# Document types
# ======================================================================

class DocumentType(str, Enum):
    EXCEL = "excel"
    CSV = "csv"
    PDF = "pdf"
    IMAGE = "image"
    TEXT = "text"
    INVOICE = "invoice"
    FORM = "form"
    TABLE = "table"
    UNKNOWN = "unknown"


# ======================================================================
# Field types for detection
# ======================================================================

class FieldType(str, Enum):
    TEXTO = "texto"
    NUMERO = "numero"
    MONEDA = "moneda"
    PORCENTAJE = "porcentaje"
    FECHA = "fecha"
    HORA = "hora"
    FECHA_HORA = "fecha_hora"
    BOOLEANO = "booleano"
    LISTA = "lista"
    EMAIL = "email"
    URL = "url"
    TELEFONO = "telefono"
    DOCUMENTO = "documento"
    CODIGO = "codigo"
    CODIGO_BARRAS = "codigo_barras"
    QR = "qr"
    TEXTAREA = "textarea"
    IMAGEN = "imagen"
    ARCHIVO = "archivo"
    RELACION = "relacion"
    # DEPRECATED: The AI should never produce 'relacion' as a field type.
    # This value is kept for legacy Campo model compatibility (users can
    # still manually set relaciones via the field editor).
    # Use codigo for any AI-generated fields that reference other entities.
    CALCULADO = "calculado"
    COLOR = "color"
    IP = "ip"
    UUID = "uuid"
    GEOLOCALIZACION = "geolocalizacion"
    DURACION = "duracion"
    ESTADO = "estado"
    CATEGORIA = "categoria"
    TAGS = "tags"


# ======================================================================
# Analysis result data classes
# ======================================================================

@dataclass
class DetectedField:
    """
    A single field detected from a document or user description.
    """
    name: str
    suggested_type: FieldType = FieldType.TEXTO
    required: bool = False
    unique: bool = False
    is_identifier: bool = False
    confidence: float = 0.0
    explanation: str = ""
    alternatives: list[str] = field(default_factory=list)
    order: int = 0
    options: Optional[list[str]] = None          # For lista type
    related_form: Optional[str] = None            # For relacion type
    formula: Optional[str] = None                 # For calculado type


@dataclass
class DetectedTable:
    """
    A table detected inside a document.
    """
    name: str
    headers: list[str]
    rows: list[list[str]]
    row_count: int = 0
    confidence: float = 0.0


@dataclass
class DocumentAnalysis:
    """
    Standard result from any document analysis.
    """
    document_type: DocumentType = DocumentType.UNKNOWN
    tables: list[DetectedTable] = field(default_factory=list)
    fields: list[DetectedField] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    confidence: float = 0.0
    warnings: list[str] = field(default_factory=list)
    raw_text: str = ""
    processing_time_ms: float = 0.0


@dataclass
class FormProposal:
    """
    A complete form proposal generated by AI.
    NOT saved to DB — just a proposal for user review.
    """
    form_name: str
    form_description: str = ""
    fields: list[DetectedField] = field(default_factory=list)
    confidence: float = 0.0
    source_document: Optional[str] = None
    warnings: list[str] = field(default_factory=list)


@dataclass
class InvoiceData:
    """
    Normalized invoice data from any source (image, PDF, scan).
    """
    provider: str = ""
    nit: str = ""
    invoice_number: str = ""
    date: str = ""
    currency: str = "COP"
    subtotal: float = 0.0
    taxes: float = 0.0
    total: float = 0.0
    items: list[dict[str, Any]] = field(default_factory=list)
    detected_fields: list[DetectedField] = field(default_factory=list)
    confidence: float = 0.0
    warnings: list[str] = field(default_factory=list)
    raw_json: Optional[dict[str, Any]] = None


@dataclass
class AIResponse:
    """
    Standard response from any AI provider call.
    """
    text: str = ""
    json_data: Optional[dict[str, Any]] = None
    model: str = ""
    provider: str = ""
    usage: dict[str, Any] = field(default_factory=dict)
    processing_time_ms: float = 0.0
    success: bool = True
    error: Optional[str] = None
    cached: bool = False


@dataclass
class ProviderConfig:
    """
    Configuration for an AI provider.
    
    SAFE: __repr__ y __str__ sanitizan api_key para evitar
    exposición accidental en logs, excepciones o serialización.
    """
    provider_type: ProviderType = ProviderType.GEMINI
    api_key: str = ""
    model: str = ""
    temperature: float = 0.1
    max_tokens: int = 4096
    timeout: int = 30  # Connection/read timeout in seconds (streaming uses this)
    extra: dict[str, Any] = field(default_factory=dict)
    
    def __repr__(self) -> str:
        return (
            f"ProviderConfig(provider_type={self.provider_type.value}, "
            f"api_key={'***' if self.api_key else ''}, "
            f"model={self.model}, temperature={self.temperature}, "
            f"max_tokens={self.max_tokens}, timeout={self.timeout})"
        )
    
    def __str__(self) -> str:
        return self.__repr__()
