# Generated by Django 5.0.14 on 2026-06-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_producto_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='MovimientoInventario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
