"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')


CLOUDINARY_URL = config('CLOUDINARY_URL', default='')
CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default='')
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default='')
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default='')

USAR_CLOUDINARY = bool(
    CLOUDINARY_URL or (
        CLOUDINARY_CLOUD_NAME and
        CLOUDINARY_API_KEY and
        CLOUDINARY_API_SECRET
    )
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.legacy.productos',
    'apps.legacy.ventas',
    'apps.shared.usuarios',
    'apps.shared.configuracion',
    'apps.shared.reportes',
    'apps.platform.dynamic_forms',
    'apps.platform.ai',
    'apps.platform.document_intelligence',
]

if USAR_CLOUDINARY:
    INSTALLED_APPS.insert(0, 'cloudinary_storage')
    INSTALLED_APPS.insert(1, 'cloudinary')

    if CLOUDINARY_URL:
        os.environ['CLOUDINARY_URL'] = CLOUDINARY_URL

    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.shared.configuracion.context_processors.configuracion_tienda',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', cast=int),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

if USAR_CLOUDINARY:
    STORAGES = {
        'default': {
            'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'


# Configuracion de correo para solicitudes de recuperacion de contraseña
# Configuracion de correo
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)

DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default='Tonjeo <no-reply@tonjeo.app>'
)

EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=20, cast=int)

ADMIN_RECOVERY_EMAIL = config(
    'ADMIN_RECOVERY_EMAIL',
    default=''
)

BREVO_API_KEY = os.environ.get("BREVO_API_KEY") or config(
    'BREVO_API_KEY',
    default=''
)
BREVO_SENDER_NAME = os.environ.get("BREVO_SENDER_NAME") or config(
    'BREVO_SENDER_NAME',
    default='Soporte'
)
BREVO_SENDER_EMAIL = os.environ.get("BREVO_SENDER_EMAIL") or config(
    'BREVO_SENDER_EMAIL',
    default=''
)

# ──────────────────────────────────────────────
# AI / LLM Provider Configuration
# ──────────────────────────────────────────────
# See apps.platform.ai for the full multi-provider architecture.
#
# To switch providers, change AI_PROVIDER and set the corresponding API key.
#
# Supported providers: gemini, openrouter, deepseek, qwen

AI_PROVIDER = config('AI_PROVIDER', default='gemini')

# API Keys for each supported provider
GEMINI_API_KEY = config('GEMINI_API_KEY', default='')
OPENROUTER_API_KEY = config('OPENROUTER_API_KEY', default='')
DEEPSEEK_API_KEY = config('DEEPSEEK_API_KEY', default='')
QWEN_API_KEY = config('QWEN_API_KEY', default='')

# Model overrides (leave empty to use provider defaults)
GEMINI_MODEL = config('GEMINI_MODEL', default='gemini-2.0-flash')
OPENROUTER_MODEL = config('OPENROUTER_MODEL', default='openai/gpt-4o-mini')
DEEPSEEK_MODEL = config('DEEPSEEK_MODEL', default='deepseek-chat')
QWEN_MODEL = config('QWEN_MODEL', default='qwen-plus')

# Shared tuning parameters
AI_TEMPERATURE = config('AI_TEMPERATURE', default=0.1, cast=float)
AI_MAX_TOKENS = config('AI_MAX_TOKENS', default=4096, cast=int)
AI_TIMEOUT = config('AI_TIMEOUT', default=30, cast=int)
AI_CACHE_DIR = config('AI_CACHE_DIR', default=BASE_DIR / '.ai_cache')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
